environment:
  password:
    secure: uOcv5TOm/CgwOmiLQhNX+g==

  matrix:
    - python : 27
    - python : 27-x64
    - python : 33
    - python : 33-x64
      DISTUTILS_USE_SDK: "1"
    - python : 34
    - python : 34-x64
      DISTUTILS_USE_SDK: "1"    
    - python : 35	
    - python : 35-x64

install:
  - "SET PATH=C:\\Python%PYTHON%;c:\\Python%PYTHON%\\scripts;%PATH%"
  - pip install -e . 

build: false

test_script:
  - python setup.py -q test -q

on_success:
  - echo Build succesful!

deploy_script:
  - echo [distutils]                                  > %USERPROFILE%\\.pypirc
  - echo index-servers =                             >> %USERPROFILE%\\.pypirc
  - echo     pypi                                    >> %USERPROFILE%\\.pypirc
  - echo [pypi]                                      >> %USERPROFILE%\\.pypirc
  - echo repository=https://pypi.python.org/pypi     >> %USERPROFILE%\\.pypirc
  - echo username=zope.wheelbuilder                  >> %USERPROFILE%\\.pypirc
  - echo password=%password%                         >> %USERPROFILE%\\.pypirc
  - set HOME=%USERPROFILE%
  - pip install wheel twine
  - ps: if($env:APPVEYOR_REPO_TAG -eq $TRUE) { python -W ignore setup.py bdist_wheel bdist_egg && twine upload dist/* }

deploy : on
